[server]
enableCORS = false
enableXsrfProtection = false

[client]
showWarningOnDirectExecution = true

[theme]
base = "dark"
primaryColor = "#FFD700"
backgroundColor = "#001f3f"
secondaryBackgroundColor = "#00264d"
textColor = "white"
font = "sans serif"
